### ISSUE TITLE
notes from meeting on 9/10/18

### ISSUE THREAD

**Issue by es2055** [ncent-archive/jobCent#6]
- Consolidated user table in the sandbox that associates keys with emails

- A screen with a list of contacts that you can quickly give jobCents to

- Integration with LinkedIn API (sign in with linkedIn)

- Display the Provenance chain of the jobCent

- Multi Cent for dealing with many different types of jobCents

- Focus UX on sending one token and less on multiple tokens

- Create a sponsor DB that associates metadata with token ID

**Comment by nakamolto** [comment]
Can you please create a separate issue for each of these?

**Comment by es2055** [comment]
yes of course. I will close this issue and create a separate issue for each then.
